    [0x00] = {['name'] = 'Keep Alive', ['decode'] = decode_0x00},
    [0x01] = {['name'] = 'Login Request', ['decode'] = decode_0x01},
    [0x02] = {['name'] = 'Handshake', ['decode'] = decode_0x02},
    [0x03] = {['name'] = 'Chat Message', ['decode'] = decode_0x03},
    [0x04] = {['name'] = 'Time Update', ['decode'] = decode_0x04},
    [0x05] = {['name'] = 'Entity Equipment', ['decode'] = decode_0x05},
    [0x06] = {['name'] = 'Spawn Position', ['decode'] = decode_0x06},
    [0x07] = {['name'] = 'Use Entity', ['decode'] = decode_0x07},
    [0x08] = {['name'] = 'Update Health', ['decode'] = decode_0x08},
    [0x09] = {['name'] = 'Respawn', ['decode'] = decode_0x09},
    [0x0A] = {['name'] = 'Player', ['decode'] = decode_0x0A},
    [0x0B] = {['name'] = 'Player Position', ['decode'] = decode_0x0B},
    [0x0C] = {['name'] = 'Player Look', ['decode'] = decode_0x0C},
    [0x0D] = {['name'] = 'Player Position & Look', ['decode'] = decode_0x0D},
    [0x0E] = {['name'] = 'Player Digging', ['decode'] = decode_0x0E},
    [0x0F] = {['name'] = 'Player Block Placement', ['decode'] = decode_0x0F},
    [0x10] = {['name'] = 'Holding Change', ['decode'] = decode_0x10},
    [0x11] = {['name'] = 'Use Bed', ['decode'] = decode_0x11},
    [0x12] = {['name'] = 'Animation', ['decode'] = decode_0x12},
    [0x13] = {['name'] = 'Entity Action', ['decode'] = decode_0x13},
    [0x14] = {['name'] = 'Named Entity Spawn', ['decode'] = decode_0x14},
    [0x15] = {['name'] = 'Pickup Spawn', ['decode'] = decode_0x15},
    [0x16] = {['name'] = 'Collect Item', ['decode'] = decode_0x16},
    [0x17] = {['name'] = 'Add Object/Vehicle', ['decode'] = decode_0x17},
    [0x18] = {['name'] = 'Mob Spawn', ['decode'] = decode_0x18},
    [0x19] = {['name'] = 'Entity: Painting', ['decode'] = decode_0x19},
    [0x1A] = {['name'] = 'Experience Orb', ['decode'] = decode_0x1A},
    [0x1B] = {['name'] = 'Stance update', ['decode'] = decode_0x1B},
    [0x1C] = {['name'] = 'Entity Velocity', ['decode'] = decode_0x1C},
    [0x1D] = {['name'] = 'Destroy Entity', ['decode'] = decode_0x1D},
    [0x1E] = {['name'] = 'Entity', ['decode'] = decode_0x1E},
    [0x1F] = {['name'] = 'Entity Relative Move', ['decode'] = decode_0x1F},
    [0x20] = {['name'] = 'Entity Look', ['decode'] = decode_0x20},
    [0x21] = {['name'] = 'Entity Look and Relative Move', ['decode'] = decode_0x21},
    [0x22] = {['name'] = 'Entity Teleport', ['decode'] = decode_0x22},
    [0x26] = {['name'] = 'Entity Status', ['decode'] = decode_0x26},
    [0x27] = {['name'] = 'Attach Entity', ['decode'] = decode_0x27},
    [0x28] = {['name'] = 'Entity Metadata', ['decode'] = decode_0x28},
    [0x29] = {['name'] = 'Entity Effect', ['decode'] = decode_0x29},
    [0x2A] = {['name'] = 'Remove Entity Effect', ['decode'] = decode_0x2A},
    [0x2B] = {['name'] = 'Experience', ['decode'] = decode_0x2B},
    [0x32] = {['name'] = 'Pre-Chunk', ['decode'] = decode_0x32},
    [0x33] = {['name'] = 'Map Chunk', ['decode'] = decode_0x33},
    [0x34] = {['name'] = 'Multi Block Change', ['decode'] = decode_0x34},
    [0x35] = {['name'] = 'Block Change', ['decode'] = decode_0x35},
    [0x36] = {['name'] = 'Block Action', ['decode'] = decode_0x36},
    [0x3C] = {['name'] = 'Explosion', ['decode'] = decode_0x3C},
    [0x3D] = {['name'] = 'Sound/Particle Effect', ['decode'] = decode_0x3D},
    [0x46] = {['name'] = 'New/Invalid State', ['decode'] = decode_0x46},
    [0x47] = {['name'] = 'Thunderbolt', ['decode'] = decode_0x47},
    [0x64] = {['name'] = 'Open Window', ['decode'] = decode_0x64},
    [0x65] = {['name'] = 'Close Window', ['decode'] = decode_0x65},
    [0x66] = {['name'] = 'Window Click', ['decode'] = decode_0x66},
    [0x67] = {['name'] = 'Set Slot', ['decode'] = decode_0x67},
    [0x68] = {['name'] = 'Window Items', ['decode'] = decode_0x68},
    [0x69] = {['name'] = 'Update Window Property', ['decode'] = decode_0x69},
    [0x6A] = {['name'] = 'Transaction', ['decode'] = decode_0x6A},
    [0x6B] = {['name'] = 'Creative Inventory Action', ['decode'] = decode_0x6B},
    [0x6C] = {['name'] = 'Enchant Item', ['decode'] = decode_0x6C},
    [0x82] = {['name'] = 'Update Sign', ['decode'] = decode_0x82},
    [0x83] = {['name'] = 'Item Data', ['decode'] = decode_0x83},
    [0xC8] = {['name'] = 'Increment Statistic', ['decode'] = decode_0xC8},
    [0xC9] = {['name'] = 'Player List Item', ['decode'] = decode_0xC9},
    [0xFE] = {['name'] = 'Server List Ping', ['decode'] = decode_0xFE},
    [0xFF] = {['name'] = 'Disconnect/Kick', ['decode'] = decode_0xFF},
